export const messageTemplate = {
  templates: [
    "**** ahead",
    "No **** ahead",
    "**** required ahead",
    "Be wary of ****",
    "Try ****",
    "Need ****",
    "Imminent ****...",
    "Weakness: ****",
    "Could this be a ****?",
    "If only I had a ****...",
    "Visions of ****...",
    "Time for ****",
    "****",
    "****!",
    "****?",
    "****...",
    "Huh. It's a ****...",
    "Let there be ****",
    "Ahh, ****...",
    "Good luck",
    "I did it!",
    "Here!",
    "I can't take this...",
    "Praise the ****!",
  ],

  categories: {
    0: [
      "Enemy",
      "Tough enemy",
      "Bar Maiden",
      "Monstrosity",
      "Beast",
      "Dwarf",
      "Golem",
      "Statue",
      "Monster",
      "Strange creature",
      "Boss",
      "Bandit",
      "Duo",
      "Trio",
      "You",
      "Good fellow",
      "Saint",
      "Charmer",
      "Poor soul",
      "Oddball",
      "Nimble one",
      "Laggard",
      "Moneybags",
      "Beggar",
      "Miscreant",
      "Liar",
      "Fatty",
      "Youth",
      "Elder",
      "Merchant",
      "Artisan",
      "King",
      "Queen",
      "Prince",
      "Princess",
      "Angel",
      "God",
      "Friend",
    ],
    1: [
      "Bonfire",
      "Ember",
      "Fog wall",
      "Humanity",
      "Lever",
      "Switch",
      "Contraption",
      "Key",
      "Torch",
      "Door",
      "Treasure",
      "Chest",
      "Something",
      "Quite something",
      "Rubbish",
      "Filth",
      "A pint",
      "Shield",
      "Projectile",
      "Armour",
      "Item",
      "Ring",
      "Trap",
    ],
    2: [
      "Close-ranged battle",
      "Ranged battle",
      "Eliminating one at a time",
      "Luring it out",
      "Beating to a pulp",
      "Lying in ambush",
      "Ambush",
      "Stealth",
      "Mimicry",
      "Pincer attack",
      "Hitting them in one swoop",
      "Dual-wielding",
      "Fleeing",
      "Charging",
      "Stabbing in the back",
      "Sweeping attack",
      "Shield breaking",
      "Head shots",
      "Sorcery",
      "Pyromancy",
      "Miracles",
      "Jumping off",
      "Sliding down",
      "Dashing through",
      "Circling around",
      "Trapping inside",
      "Rescue",
      "Pure luck",
      "Prudence",
      "Brief respite",
      "Play dead",
    ],
    3: [
      "Jog",
      "Dash",
      "Rolling",
      "Backstepping",
      "Jumping",
      "Attacking",
      "Gesture",
      "Control",
      "Destroy",
    ],

    4: [
      "Path",
      "Hidden path",
      "Secret passage",
      "Dead end",
      "Hole",
      "Shortcut",
      "Detour",
      "Illusory wall",
      "Ladder",
      "Lift",
      "Boulder",
      "Lava",
      "Poison gas",
      "Enemy horde",
      "Swamp",
      "Forest",
      "Cave",
      "Labyrinth",
      "Safe zone",
      "Danger zone",
      "Bright spot",
      "Dark spot",
      "Open area",
      "Tight spot",
      "Hiding place",
      "Exchange",
      "Gorgeous view",
      "Fall",
      "Looking away",
      "Overconfidence",
      "Slip-up",
      "Oversight",
      "Fatigue",
      "Bad luck",
      "Inattention",
      "Chance encounter",
      "Planned encounter",
    ],
    5: [
      "Front",
      "Back",
      "Left",
      "Right",
      "Up",
      "Down",
      "Feet",
      "Head",
      "Below",
      "Above",
      "Behind",
    ],
    6: [
      "Good luck",
      "Fine work",
      "I did it!",
      "I've failed...",
      "Here!",
      "Not here!",
      "I can't take this...",
      "Lonely...",
      "Don't you dare!",
      "Do it!",
      "Look carefully",
      "Listen carefully",
      "Think carefully",
      "This place again?",
      "Now the real fight begins",
      "You don't deserve this",
      "Keep moving",
      "Pull back",
      "Give it up",
      "Don't give up",
      "Help me...",
      "Impossible...",
      "Bloody expensive...",
      "Let me out of here...",
      "Stay calm",
      "Like a dream...",
      "Seems familiar...",
      "Are you ready?",
      "It'll happen to you too",
      "Praise the Sun!",
      "May the flames guide thee",
    ],
  },
};
